[tox]
skipsdist = True
usedevelop = True
skip_missing_interpreters = True

envlist = 
    python{3.9,3.10,3.11,3.12}-django4.2-wagtail{6.3,6.4}

[gh-actions]
python =
    3.9: python3.9
    3.10: python3.10
    3.11: python3.11
    3.12: python3.12

[testenv]
install_command = pip install -e ".[testing]" -U {opts} {packages}
commands = 
    coverage run testmanage.py test --deprecation all
    coverage report -m

basepython =
    python3.9: python3.9
    python3.10: python3.10
    python3.11: python3.11
    python3.12: python3.12

deps =
    coverage

    django4.2: Django>=4.2,<4.3

    wagtail6.3: wagtail>=6.3,<6.4
    wagtail6.4: wagtail>=6.4,<6.5

    lxml: lxml>=4.6
    bleach: bleach>=4.1,<4.2
    prettytable: prettytable>=2.2,<2.3
    shortcodes: shortcodes>=5.1,<6.0
    responses: responses>=0.16.0,<0.17.0
    cached_property: cached-property>=1.5.1,<1.6.0
    html5lib: html5lib>=1.1,<2.0

[testenv:flake8]
basepython=python3.9
deps=flake8>=2.2.0
commands=flake8 wagtail_wordpress_import
