[tox]
skipsdist = True
usedevelop = True
skip_missing_interpreters = True

envlist = 
    python{3.9,3.10,3.11}-django4.1-wagtail4.1

[gh-actions]
python =
    3.9: python3.9
    3.10: python3.10
    3.11: python3.11

[testenv]
install_command = pip install -e ".[testing]" -U {opts} {packages}
commands = 
    coverage run testmanage.py test --deprecation all
    coverage report -m

basepython =
    python3.9: python3.9
    python3.10: python3.10
    python3.11: python3.11

deps =
    coverage

    django4.1: Django>=4.1,<4.2

    wagtail4.1: wagtail>=4.1,<4.2

    lxml: lxml>=4.6
    bleach: bleach>=4.1,<4.2
    prettytable: prettytable>=2.2,<2.3
    shortcodes: shortcodes>=5.1,<6.0
    responses: responses>=0.16.0,<0.17.0
    cached_property: cached-property>=1.5.1,<1.6.0

[testenv:flake8]
basepython=python3.9
deps=flake8>=2.2.0
commands=flake8 wagtail_wordpress_import
