# Generated by Django 5.2.1 on 2025-05-11 13:46

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="TestPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("wp_post_id", models.IntegerField(blank=True, null=True)),
                (
                    "wp_post_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("wp_link", models.TextField(blank=True, null=True)),
                ("wp_raw_content", models.TextField(blank=True, null=True)),
                ("wp_processed_content", models.TextField(blank=True, null=True)),
                ("wp_block_json", models.TextField(blank=True, null=True)),
                ("wp_normalized_styles", models.TextField(blank=True, null=True)),
                ("wp_post_meta", models.JSONField(blank=True, null=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("rich_text", 0),
                            ("heading", 3),
                            ("image", 8),
                            ("block_quote", 9),
                            ("raw_html", 10),
                        ],
                        block_lookup={
                            0: ("wagtail.blocks.RichTextBlock", (), {}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "title"},
                            ),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h1", "H1"),
                                        ("h2", "H2"),
                                        ("h3", "H3"),
                                        ("h4", "H4"),
                                        ("h5", "H5"),
                                        ("h6", "H6"),
                                    ]
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 1), ("importance", 2)]],
                                {},
                            ),
                            4: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            6: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            7: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Left"),
                                        ("right", "Right"),
                                        ("center", "Center"),
                                    ]
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 4),
                                        ("caption", 5),
                                        ("link", 6),
                                        ("alignment", 7),
                                    ]
                                ],
                                {},
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("quote", 1), ("attribution", 5)]],
                                {},
                            ),
                            10: ("wagtail.blocks.RawHTMLBlock", (), {}),
                        },
                    ),
                ),
                (
                    "categories",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="tests.category"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
